title: CCS Computing
description: College of Creative Studies, University of California, Santa Barbara
show_downloads: true

baseurl: "/ccs-computing-site" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://hari387.github.io" # change this to the base hostname & protocol for your site

destination: docs/


# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
github:
  owner_name: CCS Computing
  owner_url: https://github.com/ucsb-ccs-computing/

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['students', 'alumni', 'faculty', 'publications']

collections:
  
  faculty:
    permalink: /faculty/:path

  students:
    permalink: /students/:path
    output: true

  alumni:
    permalink: /alumni/:path
    output: true

  courses:
    

defaults:

  - scope:
      path: ""
      type: students
    values:
      layout: person

  - scope:
      path: ""
      type: alumni
    values:
      layout: person
